language: c++
# cache: ccache

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: PYTHON_VERSION=3.4.3 OSPRAY_BUILD=OFF
    - os: linux
      dist: xenial
      compiler: gcc
      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
    - os: linux
      dist: xenial
      compiler: clang
      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
    - os: linux
      dist: xenial
      compiler: gcc
      env: PYTHON_VERSION=3.6.7 OSPRAY_BUILD=OFF
    - os: linux
      dist: bionic
      compiler: gcc
      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
#    - os: osx
#      osx_image: xcode8.3
#      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
#    - os: osx
#      osx_image: xcode10.1
#      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
    - os: osx
      osx_image: xcode10.3
      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
    - os: osx
      osx_image: xcode11
      env: PYTHON_VERSION=3.5.6 OSPRAY_BUILD=OFF
#    - os: osx
#      osx_image: xcode10.1
#      env: PYTHON_VERSION=3.6.7 OSPRAY_BUILD=OFF
    - os: osx
      osx_image: xcode11
      env: PYTHON_VERSION=3.6.7 OSPRAY_BUILD=OFF

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then date -u; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then uname -a; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build qt5-qmake qtbase5-dev libqt5opengl5-dev libqt5svg5-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja; fi
# TODO: figure out/test ccache
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
# Verify qt 5.13, maybe not upgrade
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install qt || true; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade qt || true; fi

script:
  - cd bin
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -GNinja -DTRAVIS_BUILD:BOOL=ON -DUSER_PYTHON_VERSION="${PYTHON_VERSION}" -DWITH_OSPRAY:BOOL=${OSPRAY_BUILD} -DQt5_PATH=$(brew --prefix qt) ../Superbuild; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -GNinja -DTRAVIS_BUILD:BOOL=ON -DUSER_PYTHON_VERSION="${PYTHON_VERSION}" -DWITH_OSPRAY:BOOL=${OSPRAY_BUILD} -DQt5_PATH=$(dpkg -L qtbase5-dev) ../Superbuild; fi
  - travis_wait 80 ninja # max is 50 minutes on public repository
  - cd SCIRun
  - ./Algorithm_Layer_Test
  - ./Modules_Factory_Tests --gtest_filter=*HardCodedModuleFactoryTests*

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
